[package]
name = "rite"
version = "0.1.0"
authors = ["SplittyDev <splittydev@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[profile.release]
panic = "abort"

[dependencies]
rlibc = "1.0"
spin = "0.3"
